# Uncomment the next line to define a global platform for your project
# platform :ios, '12.0'

target 'Final_Project' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
  pod "ShowAPI_SDK"
  pod "Masonry"
  pod "YCShadowView"

  # Pods for Final_Project

  target 'Final_ProjectTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'Final_ProjectUITests' do
    # Pods for testing
  end

end
